### ISSUE TITLE
Use `bun` official images

### ISSUE THREAD

**Issue by luizkowalski** [fly-apps/dockerfile-rails#86]
Hey 👋🏻 
I've been using Bun for quite some time now, and it seems stable for use with Rails.
I was checking the Docker ecosystem for Bun and turns out that they have [official images](https://hub.docker.com/r/oven/bun/tags) now. I toyed around a little bit and manage to use the official image instead of manually install Bun like this:

```dockerfile
FROM oven/bun:1 as bun

# Install node modules
COPY --link package.json bun.lockb ./
RUN --mount=type=cache,id=bld-bun-cache,target=/root/.bun \
    bun install --frozen-lockfile


FROM prebuild as build

# Install application gems
COPY --link Gemfile Gemfile.lock .ruby-version ./
RUN --mount=type=cache,id=bld-gem-cache,sharing=locked,target=/srv/vendor \
    bundle config set app_config .bundle && \
    bundle config set path /srv/vendor && \
    bundle install && \
    bundle clean && \
    mkdir -p vendor && \
    bundle config set path vendor && \
    cp -ar /srv/vendor .

# Copy bun modules
COPY --from=bun /home/bun/app/node_modules /rails/node_modules
COPY --from=bun /usr/local/bin/bun /usr/local/bun
ENV PATH=/usr/local/bun/bin:$PATH
```

Changes needed were

```diff
- FROM prebuild as bun
+ FROM oven/bun:1 as bun # it could point to version and OS like `1-alpine` and so on

# on the prebuild stage

- COPY --from=bun /rails/node_modules /rails/node_modules
+ COPY --from=bun /home/bun/app/node_modules /rails/node_modules

- COPY --from=bun /usr/local/bun /usr/local/bun
+ COPY --from=bun /usr/local/bin/bun /usr/local/bun/bin/.
```

what are your thoughts on this one?

**Comment by rubys** [comment]
Copying between base images makes me nervous.  Copying between alpine and debian, for example, is likely to cause problems.  Copying between debian bullseye and debian bookworm is likely -- but not guaranteed -- to work.

It looks like the latest bun debian image is based on 11.8 (bullseye).  The latest ruby image is based on 12.4 (bookworm).  That being said, what really matters is the output of `ldd`, for example:

```
# ldd `which bun`
	linux-vdso.so.1 (0x00007ffd5f79e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb9edd98000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb9f4281000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb9edd76000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb9edd70000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb9edc2c000)
```

What you are relying on is these files in the /lib/x86_64-linux-gnu being present in the Ruby image, which means both installed and matching the version number.  It seems that these files match (for the moment?) between 11.8 and 12.4.

Curiously, the alpine images also match the version numbers above -- it is much more common to use musl rather than libc as the runtime on alpine.  Unsurprisingly, libc is not present in the ruby:alpine image, so I suspect that the above approach will fail on alpine -- even if you are copying between oven/bun:alpine and ruby:alpine -- unless you also take care to copy the necessary files from the /lib64 directory.

**Comment by luizkowalski** [comment]
did not know that. then I think it is a bad idea

also, I checked the image size difference with copying from the base image vs installing and copying from the base image duplicates the size

bad idea overall, closing it now

thanks for the explanation!
